name: Hello world!
on:
  push:
    branches:
      - master

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/cowsay-action@v1.x
        with:
          text: "I architect, implement, administer and troubleshoot services, servers and infrastructure devices local and cloud-based"
